"""
{{Skill Name}} Plugin — Auto-generated by Skill Factory
{{description}}

Install: cp {{skill-name}}.py ~/.hermes/plugins/
Usage:   /{{skill-name}} [args]
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Plugin metadata
# ---------------------------------------------------------------------------

PLUGIN_NAME = "{{skill-name}}"
PLUGIN_VERSION = "1.0.0"
PLUGIN_DESCRIPTION = "{{description}}"


# ---------------------------------------------------------------------------
# Plugin registration
# ---------------------------------------------------------------------------

def register(hermes):
    """Register this plugin with the Hermes agent."""

    @hermes.command(
        name="{{skill-name}}",
        description="{{description}}",
        usage="/{{skill-name}} [args]",
    )
    async def run_skill(ctx, args: str = ""):
        """Execute the {{Skill Name}} workflow.

        Auto-generated from a live session by Skill Factory.
        Edit the steps below to refine the implementation.
        """
        # Step 1: {{step description}}
        # Step 2: {{step description}}
        # Step N: {{step description}}

        await ctx.reply(
            "Running **{{Skill Name}}** workflow...\n"
            "Edit `~/.hermes/plugins/{{skill-name}}.py` to implement the steps."
        )

    # Optional: register a tool this skill exposes to the AI
    # @hermes.tool(
    #     name="{{tool_name}}",
    #     description="{{tool description}}",
    # )
    # async def skill_tool(ctx, input: str) -> str:
    #     """{{Tool docstring}}"""
    #     return f"Result for: {input}"
